language: node_js
node_js:
- '5'

branches:
  only:
  - "/^v[0-9]/"

before_deploy:
- npm run build

deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: houBzg1erPPudG6Mavbd1CflTVlbT7EDzjn1xdNqsfJ4/qTfxNPvKmtc/QRjRR10iBjgt3DStlJIEba7s7JzicJmplZ6dGFVjY6/Ei7zjsGHTTdwVCshnLiIgeGXyknO2CavcgqK8vheae+fAQ0HhF6gDHYCR7+hhcFL6sN2fRLm3d2rV3iAjYcLxYIi3qzZwzcc/90N42lLOo9wpsrpiE0yz8akeRsXpQsAfESr06jCQ2Z2zpJDZx+1mHYV7y5alE6Y2htY8W+vnJvuHjl8bsVJo+agzSKIlAGvd9/rYul+i269qw6AUsb9jDE9EiPM2xE+Loe9wsM4qu2MbiObiA4Iq9IBy59FzROlEFRNVlxCCTBMqDPAk8wwJGJguET7dPG2eolwHvR5+wTJCZTGO5Bae/VA7JVRLvWtom1el0cZ7SamFi8XzUtIsXMpI3yD0M2mUfe5zC1vFAjO9iJIduvXB3XWQTcaNJADYrqz4w0pVEdgw5Noh+Yo0BbjaVtnC2NRLE21K75mRp9F6i1j7MP7yCTI3fzGwkvY6PE2aQJUKU+XGsL0Lao6F8WyJlFGVyUa7vbJbm0ByVaC0GRM8exyFwnIKAU2xIT2/96SPBUCSJ2AbAXwx3ezjuYMBouY5xpfd5XDqJdhIfe6Al6ueUrdxhWYWVGefuaF8k6Nk0E=
  on:
    tags: true
